### ISSUE TITLE
Dateパラメータ

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/GraghView#11]
度々Dateっていう名前を見るんだけど、これはx軸のこと？

**Comment by sakatore** [comment]
そう。もともと月別の支出をグラフ化するために作ったから、x軸はDateに特化させようとしました。
x軸のラベルのテキストはユーザが全部決めてもいいけど、Stringを渡さなくてもDateを１個渡せばあとはこっちでやります的な感じです。

まあDateに限定するのもあまりよくはないと思いますが、普通なやつは後からでも追加できそうですしね。

delegateとか使って"value 〇〇" , "〇〇 value" `〇〇`は自由に挿入できるようにするとかも考えてます。

**Comment by shoheiyokoyama** [comment]
その通りで、X軸をDateに絞るのはライブラリとして良くなくて、自由に設定できてDateも設定できるっいう設計にすべきだと思う。
今は、Dateに絞ってあとからX軸自由に設定できるようにするっていうのでもなしではないんだけど、なるべくそこは抽象化してほしい部分かな
