### ISSUE TITLE
GraghViewCell

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/GraghView#13]
まず、`UITableViewCell`, `UICollectionViewCell`のサブクラス以外でcellという名前をつけるのは良くないかな。

**Comment by sakatore** [comment]
「単体の」という意味を表す英語
・simple, simplicial→自分は「単純な」の意味のほうが強いけど、「単体の」でも結構使われる
・unit→意味的にはぴったりだけどお堅いイメージ
・single→単位的な意味よりかは「ひとつの」って感じ
・element→配列でも使われているからイメージしやすい

**Comment by shoheiyokoyama** [comment]
〜componentとか？

**Comment by sakatore** [comment]
いいっすね

`GraghView`もこの名前が入ってるライブラリあるから変えたほうがいいかも

**Comment by sakatore** [comment]
> ソフトウェアの分野では、特定の機能を持ち単体で完結しているが、単体では使用せず（できず）、他のプログラムから呼び出されたり連結されたりして使用されるプログラム部品のことをコンポーネントということが多い。

componentもらいますね。

**Comment by shoheiyokoyama** [comment]
👍
