### ISSUE TITLE
マイナーversionリリース

### ISSUE THREAD

**Issue by sakatore** [Kyohei-Sakai/GraghView#18]
今日中にひとまずリリースしたいです。

**Comment by shoheiyokoyama** [comment]
[Using Pod Lib Create](https://guides.cocoapods.org/making/using-pod-lib-create.html)
これに従って、今日やっちゃおう

**Comment by sakatore** [comment]
問題は名前なんですね…

**Comment by shoheiyokoyama** [comment]
plots
diagram 
record
chart

らへんが関連ワードぽいかなあ

**Comment by sakatore** [comment]
てか`Gragh`自体間違ってたわ笑
→`Graph`

**Comment by sakatore** [comment]
[`plug and chug`](http://ameblo.jp/1ppei-english/entry-11489806297.html)
とか使って、`PlugAndChugChart`, `PlugChugScrollChart`, `PCScrollableChart`

**Comment by shoheiyokoyama** [comment]
![cbevrnzukaazzjb](https://cloud.githubusercontent.com/assets/8734755/21079029/a1ffb854-bfc7-11e6-8e29-4571bbaaebc1.jpg)

**Comment by shoheiyokoyama** [comment]
いいと思うよ

**Comment by sakatore** [comment]
別のサイトで`plug 'n chug`和訳したら...
>男性が彼の立ったペニスを彼のパートナー口に差し込む、そして、彼らが音を立てて進むとき、彼のクライマックス動作は薬をうちます

**Comment by shoheiyokoyama** [comment]
わろた

**Comment by shoheiyokoyama** [comment]
それいけ

**Comment by sakatore** [comment]
比喩の表現が変な方向いっちゃったんすね笑
使うわ

**Comment by sakatore** [comment]
SSHが使えなくなってるんですけど、HTTPの方でいいですか？

**Comment by shoheiyokoyama** [comment]
pushできればなんでも可

**Comment by sakatore** [comment]
やっとできた

**Comment by shoheiyokoyama** [comment]
![LGTM](https://f.cloud.github.com/assets/1280540/389049/740410d2-a6f1-11e2-9d52-4b81d7553065.jpg)
