### ISSUE TITLE
enumのInt型

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/GraghView#2]
[GraghView.swift](https://github.com/Kyohei-Sakai/GraghView/blob/master/GraghView/GraghView.swift#L12-L25)

これIntの型宣言しているのはなぜ？

**Comment by sakatore** [comment]
`public enum UIScrollViewIndicatorStyle : Int`
`public enum UIScrollViewKeyboardDismissMode : Int`

パッと見たときにこういうのがIntだったんで、このパターンが多く使われているのかと思いました。

**Comment by shoheiyokoyama** [comment]
Obj-Cと互換性を持たせる場合とかはIntがたをつける場合があるけど、それ以外は特に意図がなければIntがたはつけなくてもいいかな。
hashValueとかで、数字の参照できるし

**Comment by sakatore** [comment]
> Obj-Cと互換性を持たせる場合とかはIntがたをつける

そういうことだったんですね。数値指定しなかったら同じになりますからね。
消しますわー

**Comment by sakatore** [comment]
enumを管理する場所ってどこがいいんですか？
`GraghView`の中に入れるのか、外でいいのか？

**Comment by shoheiyokoyama** [comment]
internalなアクセスレベルのものは中に入れちゃっていいけど、publicなものは外でいいかなーって思ってる。classの中に入れちやうと、外から値変えるときに冗長になっちゃうからね。その分グローバルなenumになってしまうから、名前はちゃんとつけないといけないけどね。

```swift
class AClass {
    enum Type { case one, two }
 }

//冗長
A.type = AClass.Type.one
```
