### ISSUE TITLE
関数ジャンプ

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/GraghView#5]
`// MARK: Only Bar`

これ
`//MARK: - `
じゃないとジャンプできなくない？

**Comment by sakatore** [comment]
<img width="304" alt="screenshot" src="https://cloud.githubusercontent.com/assets/19564003/20859118/fc540af6-b998-11e6-8106-23b36b8c6823.png">

ジャンプってここ使ってですよね？
それなら出来てますよ。

**Comment by shoheiyokoyama** [comment]
あ、できるのか。じゃあ俺の勘違いだわ。
一般的には　`//MARK: -`こういう風に-が使われてる場合が多いと思うよ
